version: 2
jobs:
  build:
    docker:
      - image: python:3.9.2-slim
    steps:
      - run: pip install platformio==5.1.1
      - checkout
      - run: >
          pushd firmware
          platformio run
          popd
          pushd config-tool
          ./protoc.sh
          go build
          popd

