version: 2
jobs:
  build:
    docker:
      - image: python:2.7
    steps:
      - run: pip install platformio
      - checkout
      - run: cd embedded
      - run: platformio lib install 31 89 166 1089
      - run: platformio run

